version: '3.9'
name: chat
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
    volumes:
      - ./postgres_data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data/db:/var/lib/postgresql
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak
    command: "start-dev --import-realm"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/chat-realm.json
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass

    ports:
      - "8000:8080"
      - "9000:9000"

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
